# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Luci18 for smartdns server
LUCI_DEPENDS:=+smartdns-new
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-smartdns-new-18
PKG_VERSION:=2
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
